### ISSUE TITLE
Unable to delete the user

### ISSUE THREAD

**Issue by dalonlobo** [jupyterhub/firstuseauthenticator#14]
Hi Team,

I'm unable to delete the user. Following are the logs from the hub. I'm running Jupyterhub on Kubernetes using AKS.

```
[E 2018-12-06 11:33:32.653 JupyterHub web:1670] Uncaught exception DELETE /hub/api/users/test2 (10.240.0.5)
    HTTPServerRequest(protocol='https', host='codelab.videoken.com', method='DELETE', uri='/hub/api/users/test2', version='HTTP/1.1', remote_ip='10.240.0.5')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/apihandlers/users.py", line 169, in delete
        await maybe_future(self.authenticator.delete_user(user))
      File "/home/jovyan/.local/lib/python3.6/site-packages/firstuseauthenticator/firstuseauthenticator.py", line 76, in delete_user
        del db[user.name]
    KeyError: 'test2'

[E 2018-12-06 11:33:32.655 JupyterHub log:150] {
      "Content-Length": "0",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1544094833|20:jupyterhub-hub-login|44:ZTA1NDNhNDAwYzdmNGM4NGI0Yzc5MmI3MTFkYTI2ZDc=|3d521771d55cf3373cb578f682581e7c471aea1599fcd4d8a9cafcc73ad83504\"; jupyterhub-
session-id=da2803f570b9422e822e0624116a1afe; _xsrf=2|c90a95be|7f69e28f7cfe7a6f8173c46c077d2fe2|1544094835",
      "Dnt": "1",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Type": "application/json",
      "Referer": "https://codelab.videoken.com/hub/admin?sort=last_activity&order=desc&",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0",
      "X-Scheme": "https",
      "X-Original-Uri": "/hub/api/users/test2",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "codelab.videoken.com",
      "X-Forwarded-For": "10.240.0.5,10.244.7.11",
      "X-Real-Ip": "10.240.0.5",
      "X-Request-Id": "05e2533cca1637631edc97a29a4b220c",
      "Connection": "close",
      "Host": "codelab.videoken.com"
    }
```

Thank you for your help in advance.

**Comment by dalonlobo** [comment]
I created the user from hub admin page, but I did not login with that user. So the username does not exist in the passwords db, hence it was not able to delete them. Closing the issue now.
