### ISSUE TITLE
No module named 'firstuseauthenticator'

### ISSUE THREAD

**Issue by iliang** [jupyterhub/firstuseauthenticator#25]
Hi, when running jupyterhub, I get the error message.
I have tried python import firstuseauthenticator using root privilage successful, but when I using " sudo -u rhea python -c  "import firstuseauthenticator" "  that shows no No module named 'firstuseauthenticator'

```
[C 2019-09-04 14:24:43.316 JupyterHub application:90] Bad config encountered during initialization:
[C 2019-09-04 14:24:43.316 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f437dd7ad30> instance must be a type, but 'firstuseauthentica        tor.FirstUseAuthenticator' could not be imported
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /opt/miniconda3/lib/python3.7/site-packages/jupyterhub/app.py:2477> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 1576, in validate
    value = self._resolve_string(value)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 1507, in _resolve_string
    return import_item(string)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'firstuseauthenticator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 603, in load_config_file
    self.update_config(new_config)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 198, in update_config
    self._load_config(config)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 153, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 559, in set
    new_value = self._validate(obj, value)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/opt/miniconda3/lib/python3.7/site-packages/jupyterhub/traitlets.py", line 154, in validate
    return super().validate(obj, value)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/traitlets.py", line 1579, in validate
    "%r could not be imported" % (self.name, obj, value))
traitlets.traitlets.TraitError: The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f437dd7ad30> instance must be a type, but 'firstuseauthenticator.FirstUseAuthentica        tor' could not be imported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2492, in launch_instance
    loop.start()
  File "/opt/miniconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/opt/miniconda3/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/opt/miniconda3/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/opt/miniconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/miniconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
    await self.initialize(argv)
  File "/opt/miniconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2088, in initialize
    self.load_config_file(self.config_file)
  File "</opt/miniconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-5>", line 2, in load_config_file
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 93, in catch_config_error
    app.exit(1)
  File "/opt/miniconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 648, in exit
    sys.exit(exit_status)
SystemExit: 1
```

**Comment by consideRatio** [comment]
In your logs I see:

```
[C 2019-09-04 14:24:43.316 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f437dd7ad30> instance must be a type, but 'firstuseauthentica        tor.FirstUseAuthenticator' could not be imported
```

It seems like your string to set the authenticator contain many spaces.

The error is a common Python error occurring when source code isn't found, so the question is why. I don't have a clear idea on how to debug it other than tro to run python the way JupyterHub would be run by python and try to make sure firstuseauthenticator is installed properly to that python using `pip`.

**Comment by consideRatio** [comment]
Feel free to reopen this issue if you want further help, but it as it is not related to the code base itself of this repository, I'll close this for now. :sunflower:
