### ISSUE TITLE
500 Error on path /hub/auth/change-password

### ISSUE THREAD

**Issue by swill** [jupyterhub/firstuseauthenticator#36]
### Bug description
According to this documentation (https://tljh.jupyter.org/en/latest/howto/auth/firstuse.html) a logged in user should be able to change their password by navigating to /hub/auth/change-password, however a 500 error is thrown when you attempt to navigate to this URL.

#### Expected behaviour
I would expect a "change password" screen to be shown where I could change my current password.

#### Actual behaviour
I receive a 500 error in the browser.  The following details are output in the logs.

```
[E 2021-06-16 15:13:59.925 JupyterHub web:1789] Uncaught exception GET /hub/auth/change-password (10.1.2.1)
    HTTPServerRequest(protocol='http', host='minio.infojutras.com:8000', method='GET', uri='/hub/auth/change-password', version='HTTP/1.1', remote_ip='10.1.2.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/firstuseauthenticator/firstuseauthenticator.py", line 64, in get
        self.finish(html)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 172, in finish
        super().finish(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1127, in finish
        self.write(chunk)
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 841, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
    
[E 2021-06-16 15:13:59.949 JupyterHub log:173] {
      "X-Forwarded-Host": "minio.infojutras.com:8000",
      "X-Forwarded-Port": "8000",
      "Upgrade-Insecure-Requests": "1",
      "Cookie": "jupyterhub-hub-login=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
      "Dnt": "1",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-CA,en-US;q=0.7,en;q=0.3",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
      "Host": "minio.infojutras.com:8000",
      "X-Forwarded-Proto": "http,http",
      "X-Forwarded-For": "10.1.2.1,::ffff:10.42.3.0",
      "X-Real-Ip": "10.1.2.1",
      "Connection": "close"
    }
[E 2021-06-16 15:13:59.949 JupyterHub log:181] 500 GET /hub/auth/change-password (swill@10.1.2.1) 28.04ms
```

### How to reproduce
Configure the First Use Authenticator package in your JuypterHub deployment.

The relevant configuration details from my helm values are:
```
hub:
  config:
    Authenticator:
      admin_users:
        - swill
    FirstUseAuthenticator:
      create_users: false
    JupyterHub:
      authenticator_class: 'firstuseauthenticator.FirstUseAuthenticator'
      admin_access: true
```

1. Login with an existing user (if the first time, set your password)
2. Once logged in, paste the following path into the url: `/hub/auth/change-password`
3. Observe the 500 error
4. Review the logs with: `kubectl logs hub-xxxxxxxx-yyyyy -n jhub`

### Your personal set up
JupyterHub deployed with the following:

```
# Helm release name
RELEASE=jhub
# k8s namespace
NAMESPACE=jhub
# Helm chart version
CHARTVERSION=0.11.1

helm upgrade --cleanup-on-fail \
  --install $RELEASE jupyterhub/jupyterhub \
  --namespace $NAMESPACE \
  --create-namespace \
  --version=$CHARTVERSION \
  --values jhub-config.yaml
```

 - OS:
Ubuntu 20.04 + Kubernetes (RKE2) v1.19.8+rke2r1

**Comment by georgejhunt** [comment]
I created a pull request #37 for this issue. 
The coroutine needs to fetch the template content before it can be displayed. 
I had to read up about asyncio to come up with this proposed fix.
